---
title: "pMan Paper"
author: "Kirsten Refvik"
date: "3/18/2023"
output: html_document
---
Using R4.2.2
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Libraries
```{r}
library(ragg)
library(dplyr)
library(limma)
library(Glimma)
library(edgeR)
library(ggplot2)
library(VennDiagram)
library(ggvenn)
library(EnhancedVolcano)
```


Load Data
```{r}

x4 = readRDS("C:/Users/kirst/Desktop/Papers in progress/pGalpMangroupsCD4adj.rds")
x8 = readRDS("C:/Users/kirst/Desktop/Papers in progress/pGalpMangroupsCD8adj.rds")
x  = readRDS("C:/Users/kirst/Desktop/Papers in progress/pGalpMangroupsadj.rds")

#Isolate pMan Data from pGal
x <- x[,c(1,3:6,8:23,25:29,31:39), keep.lib.sizes=FALSE]
x4 <- x4[,c(1,5:15,18:19), keep.lib.sizes=FALSE]
x8 <- x8[,c(4:16,19:20), keep.lib.sizes=FALSE]
```

Design Matrix - x
Code for CD4/CD8 comparison 
```{r}
group <- x$samples[,7]
batch <- x$samples[,9]
design4 <- model.matrix(~0+group+batch)
colnames(design4) <- gsub("group", "", colnames(design4))
colnames(design4) <- gsub("batch2", "batch", colnames(design4))
contr.matrix <- makeContrasts(
  CD4vsCD8 = CD4 - CD8,
  levels = colnames(design4))

par(mfrow=c(2,2))
v4 <- voomWithQualityWeights(x,design4, plot=TRUE)
```


Design Matrix - x4 and x8 - separate
```{r}
###cd4###
group <- x4$samples[,1]
batch <- x4$samples[,9]
design4 <- model.matrix(~0+group+batch)
colnames(design4) <- gsub("group", "", colnames(design4))
colnames(design4) <- gsub("batch2", "batch", colnames(design4))
contr.matrix4 <- makeContrasts(
  pManvsSaline = pMan - Saline,
  pManvsOVA = pMan - OVA,
  OVAvsSaline = OVA - Saline, 
  levels = colnames(design4))
contr.matrix <-contr.matrix4

par(mfrow=c(2,2))
v4 <- voomWithQualityWeights(x4,design4, plot=TRUE)

###cd8###
group <- x8$samples[,1]
batch <- x8$samples[,9]
design8 <- model.matrix(~0+group+batch)
colnames(design8) <- gsub("group", "", colnames(design8))
colnames(design8) <- gsub("batch2", "batch", colnames(design8))
contr.matrix8 <- makeContrasts(
  pManvsSaline = pMan - Saline,
  pManvsOVA = pMan - OVA,
  OVAvsSaline = OVA - Saline, 
  levels = colnames(design8))
par(mfrow=c(2,2))
v8 <- voomWithQualityWeights(x8,design8, plot=TRUE)
```


```{r}
#vfit
vfit <- lmFit(v4, design4)
vfit <- contrasts.fit(vfit, contrasts=contr.matrix)
efit <- eBayes(vfit)
plotSA(efit, main="Final model: Mean-variance trend for CD4")

v8fit <- lmFit(v8, design8)
v8fit <- contrasts.fit(v8fit, contrasts=contr.matrix8)
e8fit <- eBayes(v8fit)
plotSA(e8fit, main="Final model: Mean-variance trend for CD8")

```

Differentially expressed genes: by the numbers
```{r}
######  CD4  #####
### no additional cutoff p = 0.05 ###
x4degsum1 = summary(decideTests(efit))
print("p=0.05 cutoff alone")
x4degsum1

### add 1.5 fold change cutoff (0.58 lfc) ###
tfit =  treat(vfit, lfc=0.58)
x4degsum2 = summary(decideTests(tfit))
print("1.5-fold cutoff")
x4degsum2

### 1.2 fold change cutoff (0.26 lfc) ###
t2fit = treat(vfit,lfc = 0.26)
x4degsum3 = summary(decideTests(t2fit))
print("1.2-fold cutoff")
x4degsum3
```

```{r}
####### CD8  #######
### no additional cutoff p = 0.05 ###
x8degsum1 = summary(decideTests(e8fit))
print("p=0.05 cutoff alone")
x8degsum1

### add 1.5 fold change cutoff (0.58 lfc) ###
t8fit =  treat(v8fit, lfc=0.58)
x8degsum2 = summary(decideTests(t8fit))
print("1.5-fold cutoff")
x8degsum2

### add 1.2 fold change cutoff (0.26 lfc) ###
t82fit = treat(v8fit,lfc = 0.26)
x8degsum3 = summary(decideTests(t82fit))
print("1.2-fold cutoff")
x8degsum3

```
Lists of DEGs
```{r}
#create list of DE genes for CD4 groups
pMan.vs.saline = topTable(efit,Inf,coef=1, sort.by="P",adjust.method = "BH")
pMan.vs.OVA <- topTable(efit,n=Inf,coef=2, sort.by="P",adjust.method = "BH")
OVA.vs.saline <- topTable(efit,n=Inf,coef=3, sort.by="P",adjust.method = "BH")

#create list of DE genes for CD8 groups
pMan.vs.saline8 <- topTable(e8fit,n=Inf,coef=1, sort.by="P",adjust.method = "BH")
pMan.vs.OVA8 <- topTable(e8fit,n=Inf,coef=2, sort.by="P",adjust.method = "BH")
OVA.vs.saline8 <- topTable(e8fit,n=Inf,coef=3, sort.by="P",adjust.method = "BH")
```

Write to csv
***Input for IPA***
```{r}
###  CD4  ###
write.csv(pMan.vs.saline,file = "pManvsSalineadjCD4DEGList.csv")
write.csv(pMan.vs.OVA,file = "pManvsOVAadjCD4DEGList.csv")
write.csv(OVA.vs.saline,file = "OVAvsSalineadjCD4DEGList.csv")

###  CD8  ###
write.csv(pMan.vs.saline8,file = "pManvsSalineadjCD8DEGList.csv")
write.csv(pMan.vs.OVA8,file = "pManvsOVAadjCD8DEGList.csv")
write.csv(OVA.vs.saline8,file = "OVAvsSalineadjCD8DEGList.csv")
```

Venn Diagram
```{r}
# All three groups ###
results = decideTests(vfit,adjust.method="BH",p=0.05)
vennDiagram(results,names=c("pMan vs. Saline", "pMan vs. OVA", "OVA vs. Saline"),cex = c(1.4),circle.col = c("#FF66FF","#6633FF","#33F399"))


#### pMan-OVA and OVA vs Saline ####
z = decideTests(vfit,adjust.method="BH",p=0.05)
pManvsSalineVenn  =  which(z[,1]!=0)
OVAvsSalineVenn   =  which(z[,3]!=0)
set1              =  t2fit$genes$gene_name[OVAvsSalineVenn]
set2              =  t2fit$genes$gene_name[pManvsSalineVenn]
x                 =  list(pMan=set2, OVA=set1)

ggvenn(x, show_percentage = FALSE,stroke_size=,set_name_size = 8,text_size = 6,fill_color = c("purple","cyan") )
```
Volcano Plot - pMan-OVA vs OVA in OTII (Paper edition + interactive)
```{r}
pmanova = topTable(efit,n=Inf,coef=2)
EnhancedVolcano(pmanova,
                lab = pmanova$gene_name,
                x = 'logFC',
                y = 'adj.P.Val',
                title = 'pMan vs OVA',
                subtitle = NULL,
                xlim=c(-6,6),
                ylim = c(0, -log10(10e-6)),
                FCcutoff=1.5,
                pCutoff = 0.05,
                #pLabellingCutoff = 0.001,
                cutoffLineType = 'blank',
                pointSize = 2.0,
                labSize = 5.0,
                legendLabels = c('NS', expression(Log[2]~FC>1.5), "p-value<0.05", expression(p-value<0.05~and~log[2]~FC>1.5)),
                legendPosition = 'bottom',
                legendLabSize = 12,
                legendIconSize =3.0,
                #col = c("black","12979G","#8A6FB1","#EE226F"),
                colAlpha = 0.7,
                drawConnectors = TRUE,
                typeConnectors = 'open',
                gridlines.minor = FALSE,
                boxedLabels = TRUE
                #labhjust = 0.5
                )+
  theme(plot.title = element_text(hjust = 0.5))
ggsave(filename = "pManOVAVolcano.png", width = 20, height =20, units = 'cm')

```
```{r}
#pManvsOVA CD4
 sample.cols       = c("purple", "deeppink2", "deepskyblue1")[x4$sample$group]
 TpMan.vs.OVA      = topTable(efit,n=Inf,coef=2)
 lcpm4             = cpm(x4, log=TRUE)
 adjP              = TpMan.vs.OVA$adj.P.Val
 logFC             = TpMan.vs.OVA$logFC
 neg.log10P        = -log10(adjP)
 de1               = as.integer(adjP <= 0.05 & !is.na(adjP) & logFC >= 1)
 de2               = -as.integer(adjP <= 0.05 & !is.na(adjP) & logFC <= -1)
 de3               = which(de2!=0)
 de4               = replace(de1, de3, -1)
 
 row.order <- TpMan.vs.OVA$gene
 lcpmnew<-lcpm4[row.order,]
 
 glXYPlot(x=logFC, y=neg.log10P, xlab="logFC", ylab="-log10P", status=de4,
          side.ylab="Log-CPM", main="pMan vs OVA CD4",
          counts=lcpmnew, 
          groups=x4$sample$group,
          sample.cols=sample.cols, 
          anno=TpMan.vs.OVA[, c("gene", "gene_name", "adj.P.Val")],
          side.main = "gene_name",
          folder = "pManvsOVAvolcano",
          html = "ManvsOVACD4")
 
```

